/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "nwa.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(EmulatorInfoRequest, EmulatorInfoRequest, AUTO)


PB_BIND(EmulatorInfoResponse, EmulatorInfoResponse, AUTO)


PB_BIND(EmulationStatusRequest, EmulationStatusRequest, AUTO)


PB_BIND(EmulationStatusResponse, EmulationStatusResponse, AUTO)


PB_BIND(CoreMemoriesRequest, CoreMemoriesRequest, AUTO)


PB_BIND(CoreMemory, CoreMemory, AUTO)


PB_BIND(CoreMemory_PropertiesEntry, CoreMemory_PropertiesEntry, AUTO)


PB_BIND(CoreMemoriesResponse, CoreMemoriesResponse, AUTO)


PB_BIND(MemoryRegion, MemoryRegion, AUTO)


PB_BIND(MemoryRegionData, MemoryRegionData, AUTO)


PB_BIND(CoreMemoryReadRequest, CoreMemoryReadRequest, AUTO)


PB_BIND(CoreMemoryReadResponse, CoreMemoryReadResponse, AUTO)


PB_BIND(CoreMemoryWriteMultiRequest, CoreMemoryWriteMultiRequest, AUTO)


PB_BIND(CoreMemoryWriteMultiResponse, CoreMemoryWriteMultiResponse, AUTO)


PB_BIND(CoreMemoryReadMultiRequest, CoreMemoryReadMultiRequest, AUTO)


PB_BIND(CoreMemoryReadMultiResponse, CoreMemoryReadMultiResponse, AUTO)


PB_BIND(CoreMemoryWriteRequest, CoreMemoryWriteRequest, AUTO)


PB_BIND(CoreMemoryWriteResponse, CoreMemoryWriteResponse, AUTO)





